# --- 데이터 경로 설정 ---
dataset_type: 'coco-17'

state_map: {'stand': 0, 'sit': 1, 'lying': 2}
column_format: '{name}{suffix}'
x_suffix: '_x'
y_suffix: '_y'

# 프로젝트 전반에서 사용되는 데이터 및 모델 저장 경로를 정의합니다.
data_paths:
  raw_dir: 'data/Raw'          # 원본 데이터 디렉터리
  processed_dir: 'data/Processed' # 정규화 등 전처리된 데이터 디렉터리
  results_dir: 'results'      # 예측 결과가 저장될 디렉터리
  h5_dir: 'data'               # H5 포맷으로 변환된 학습 데이터 디렉터리
  model_dir: 'models'          # 학습된 모델이 저장될 디렉터리

HEADER_KEYPOINTS: [
    "nose", "left_eye", "right_eye", "left_ear", "right_ear",
    "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
    "left_wrist", "right_wrist", "left_hip", "right_hip",
    "left_knee", "right_knee", "left_ankle", "right_ankle"
]

PROCESSED_KEYPOINTS: [
    'nose', 'eye_l', 'eye_r', 'ear_l', 'ear_r', 
    'shoulder_l', 'shoulder_r', 'elbow_l', 'elbow_r', 
    'wrist_l', 'wrist_r', 'hip_l', 'hip_r', 
    'knee_l', 'knee_r', 'ankle_l', 'ankle_r'
]

# --- 모델별 하이퍼파라미터 설정 ---
models:
  model1:
    name: 'State_Classifier'
    data:
      keypoint_indices: [5, 6, 11, 12, 13, 14] # 사용할 관절 인덱스
      seq_length: 30
    architecture:
      num_classes: 3
      d_model: 64
      n_head: 4
      num_layers: 2
      ffn_dim: 128
    training:
      batch_size: 32
      num_epochs: 20
      learning_rate: 0.001
